project:
  type: website
  output-dir: docs
  render:
    - "/index.qmd"
  resources:
    - image
    - bayesjuku_2022summer
    - japanr2021lt

website:
  title: Slides list
  description: Slides created with quarto
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/Masakazoo
  repo-url: https://github.com/Masakazoo/slide
  repo-actions: source

format:
  html:
    theme:
      light: flatly
      dark: darkly

lang: ja
